### ISSUE TITLE
Aufgabe5

### ISSUE THREAD

**Issue by Ronjaaa** [Ronjaaa/GIS_SoSe2020#1]
Aus irgend einem Grund wird bei mir nur die zweite Kategorie angezeigt und Buttons werden auch nicht angezeigt. Ich kann nicht finden woran das liegt.

**Comment by Ronjaaa** [comment]
Ich habe meinen button code 10.000 mal geändert aber er wird einfach nie angezeigt. Könnt ihr mir vielleicht einen Tipp geben woran das liegt?

**Comment by Plagiatus** [comment]
wir bekommen das nicht mit, wenn du in deinem eigenen Repo ein issue schreibst. bitte im allgemeinen Repo das Issue schreiben.

- ich sehe bei dir nur js Dateien, keine ts dateien. und dementsprechend auch keine typisierung.
- warum bindest du das skript am Ende des bodies ein?
- und das Problem mit deinem Button ist wahrscheinlich, dass du versuchst ein "submit" (statt "button") element zu erstellen, was es nicht gibt. 

außerdem hast du ähnliche Probleme wie viele andere auch (keine Ampel dafür):
- Warum ist der Preis ein string?
- zwei Arrays und zwei for schleifen, welche fast genau das gleiche tun.
- wenn du das div element schon anlegst, dann brauchst du es nicht jedes mal mit dem queryselector wieder herausfischen

**Comment by Ronjaaa** [comment]
Oh okay das wusste ich nicht.

Ich werde die ts Datei nachtragen.

Ich binde das Script am ende vom body ein weil ich gegoogelt habe wie es zu machen ist und alle gesagt haben es muss da sein damit das html und css Dokument zuerst lädt.

Mit dem button habe ich wie gesagt den code 10.000n mal geändert vorher stand da auch mal button aber es hat halt nie funktioniert weswegen ich es versucht habe zu ändern. Ich weiß immer noch nicht wie es geht und habe auch in der klasse nachgefragt und niemand konnte mir helfen. Egal was ich eingebe mein button wird einfach nie angezeigt.

Ich dachte es ist einfacher den preis als String  zu schreiben wegen dem euro Zeichen

Ich habe zwei arrays weil die zwei Kategorien in meinem html Dokument ja getrennt sind und ich nicht will das alles unterer ersten Kategorie steht.

**Comment by Plagiatus** [comment]
> Ich werde die ts Datei nachtragen.

und bitte auch die js.map dateien. Du musst die ja aktiv ausgeschaltet haben damit das nicht funktioniert hat.

> Ich binde das Script am ende vom body ein weil ich gegoogelt habe wie es zu machen ist und alle gesagt haben es muss da sein damit das html und css Dokument zuerst lädt.

Es haben bestimmt nicht "alle" gesagt. Ich habe z.B. in meinem Video gesagt, dass das Skript tag in den head gehört, was auch der eigentliche Konsens ist. Es gibt dann zwei Möglichkeiten, dass das Skript erst ausgeführt wird, nachdem die Seite geladen ist:
1. das `defer` Attribut (wird auch im Video kurz erklärt, sorgt vorallem einfach dafür, dass die Seite fertig geladen wird, bevor das skript geladen wird)
2. ein Eventlistener auf window oder document, welcher darauf reagiert dass es jeweils fertig geladen ist.

> Mit dem button habe ich wie gesagt den code 10.000n mal geändert vorher stand da auch mal button aber es hat halt nie funktioniert weswegen ich es versucht habe zu ändern. Ich weiß immer noch nicht wie es geht und habe auch in der klasse nachgefragt und niemand konnte mir helfen. Egal was ich eingebe mein button wird einfach nie angezeigt.

Mal mit dem Debugger rein geschaut? ansonsten können wir da gerne mal zusammen im Praktikum nachschauen.

> Ich dachte es ist einfacher den preis als String zu schreiben wegen dem euro Zeichen

Auch nur so lange bis du damit rechnen sollst. Und das € Zeichen kannst du doch auch so hinzufügen? `produkt.preis + "€"`

> Ich habe zwei arrays weil die zwei Kategorien in meinem html Dokument ja getrennt sind und ich nicht will das alles unterer ersten Kategorie steht.

Es gibt noch mehr Möglichkeiten, eine Element-Kategorie von einer anderen zu unterscheiden, als zwei verschiedene Arrays pflegen zu müssen.
